[package]
name = "poker-lookup-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = "0.11"
phf_codegen = "0.11"
poker = { path = "../poker" } # Local
